site_name: CZ_OpenSpice-Docs
pages:
    - 简要介绍: Home/index.md 
    - 使用手册: 
        - 使用详解: Guide/guide_1.md 
        - 元件属性: Guide/guide_2.md
        - 仿真设置: Guide/guide_3.md
    - 样例示范:
        - 直流扫描: Demo/demo_1.md
        - 瞬态仿真: Demo/demo_2.md
        - 交流仿真: Demo/demo_3.md
        - 视频讲解: Demo/demo_4.md

    - 关于: About/about.md
theme: readthedocs
